# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e12900736bc9440a92e9469e1dd3856212f23fabf9641a56d1a97cceb7b4f158aa346ee89bf286b4eb44a2913ad2ba6743643bdcdde0e26ca0c1c800259b3614

test:
  secret_key_base: a0cf5d730348a734c28e2a61514a79bf15a456c650382d2c064f00cd262ca9e3a967dbcd740f4592c4595b7b8dbe3f58b96a40cba67cb6910dd5eb26f68ef722

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
